export enum FrameworksName {
  ios = "iOS",
  android = "Android",
  web = "Web",
  react = "React Native",
  cordova = "Cordova",
  xamarinForms = "Xamarin Forms",
  flutter = "Flutter",
  kmp = "Kotlin Multiplatform",
  capacitor = "Capacitor",
  titanium = "Titanium",
  linux = "Linux",
  xamarinIos = "Xamarin iOS",
  xamarinAndroid = "Xamarin Android",
  netAndroid = ".NET Android",
  netIos = ".NET iOS",
  net = ".NET",
  xamarin = "Xamarin",
}
